name: Build

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  linux_build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release

    - shell: bash
      run: |
        mv target/release/qr_code_creator qr_code_creator
        chmod 777 qr_code_creator
        tar cpfz qr_code_creator_linux_x86_64.tar.gz qr_code_creator
        
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: qr_code_creator_linux_x86_64.tar.gz

  win_build:
    runs-on: windows-latest
    steps:
    - name: Install rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        target: x86_64-pc-windows-msvc
        override: true

    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --release

    - shell: bash
      run: |
        mv target/release/qr_code_creator qr_code_creator
        7z a qr_code_creator_windows_x86_64.zip qr_code_creator.exe
        
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: qr_code_creator_windows_x86_64.zip
